[default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/c4d26f80153d415383d9b06e7eaec865"
rinkeby = "https://rinkeby.infura.io/v3/c4d26f80153d415383d9b06e7eaec865"
